%YAML:1.0
enhmod_0: 1
enhparm_1: 4.0
mmtdparm_2: 10
mmtdparm_3: 80
mmtdparm_4: 3600
mmtdparm_5: 6
mmtdparm_6: 16
mmtdparm_7: 1.25
mmtdparm_8: 50
timedisp_9: 1
calib_x_1: 965
calib_y_1: 545
calib_x_2: 960
calib_y_2: 540
calib_x_3: 955
calib_y_3: 535
calib_x_4: 960
calib_y_4: 540
